### ISSUE TITLE
OSError:[Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by tianyilt** [johnnychen94/ecnu-net-login#1]
学长您好,我在实验室放了一个ubuntu20.04的服务器,之前饱受校园网 超过30分钟自动注销 的问题困扰,在使用了你们的脚本之后,坚持了一段时间,可惜还是中断了
## 错误复现
```
ecnu_net --update
ecnu_net --login --daemon
```
其中`ecnu_net --update`是明文存储密码的

之后服务突然断了,我联系同学帮忙看一下,当他第一时间进行登录的时候
![image](https://user-images.githubusercontent.com/41582525/97770824-c678ec00-1b71-11eb-87bf-dbceccf6e31f.png)

网页出现错误,而且没有返回结果
之后同学插拔网线,再进入登录页面登录后成功了
我通过向日葵远程桌面软件进入查看后,发现问题出现在以下位置
![image](https://user-images.githubusercontent.com/41582525/97770706-9f6dea80-1b70-11eb-8be2-f5dc4c6ea746.png)

**Comment by tianyilt** [comment]
我检查了一下,可能是dns偶尔查不到,或许可以异常处理一下,让get_ip等几秒再去查

**Comment by tianyilt** [comment]
现在是第二次遇到这个情况,错误记录如下:
```
Wed Nov 18 18:53:41 2020
check internet connection...
Login...
check internet connection...
Wed Nov 18 18:55:42 2020
check internet connection...
Login...
check internet connection...
Wed Nov 18 18:57:43 2020
Traceback (most recent call last):
  File "/usr/local/bin/ecnu_net", line 282, in <module>
    main()
  File "/usr/local/bin/ecnu_net", line 260, in main
    Loginer(POSTDATA_TEMPLATE, force_reread=False)
  File "/usr/local/bin/ecnu_net", line 135, in __init__
    self._postdata['user_ip'] = get_ip(DNS_SERVER)
  File "/usr/local/bin/ecnu_net", line 114, in get_ip
    tmp_socket.connect((dns, 80))
OSError: [Errno 101] Network is unreachable
```
这个是我给ubuntu2004服务器用的自动登录,目前看上去好像这个脚本会在长时间运行后突然连校园网内网也无法访问(不能访问校园网的dns服务器)
但是只要把网线插拔后又可以通过
```
nohup ecnu_net --login --verbose --daemon >> ecnu_net.log 2>&1 &
```
访问校园网.
而且推翻了我之前的猜测,等一段时间还是访问不了dns服务器

**Comment by johnnychen94** [comment]
初步估计是 DNS 解析的问题，你们的网络是如何配置的？

可以看一下你的 `/etc/resolv.conf` 的内容么？这个文件定义了DNS解析使用的DNS服务器，有多个工具可能会自动刷新该文件。我这边是通过 `systemd-resolvd`来配置该文件的，比如说：

```text
# /etc/systemd/resolvd.conf

[Resolve]
DNS=202.120.80.1 223.5.5.5
#FallbackDNS=
Domains=ecnu.edu.cn
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#Cache=yes
#DNSStubListener=yes
```

然后 `service systemd-resolvd restart`之后，dns解析应该就正常了。这里 `202.120.80.1` 是校园网内的dns服务器。

---

抱歉之前 mute 了这个仓库所以没收到提醒，没想到还有其他人在用hhhhh

**Comment by tianyilt** [comment]
谢谢学长的回复,`/etc/resolv.conf`运行结果如下
```
$ cat /etc/resolv.conf                                                                                                                                  [17:32:32]
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
(base) 

```
我试试看直接修改这个文件。

**Comment by johnnychen94** [comment]
closed by 1e354f583d87d25b7289aaf5234b03725e5527af

我之前也偶尔遇到过类似的问题，不过一直没去修复...

**Comment by johnnychen94** [comment]
https://github.com/johnnychen94/ecnu-net-login/blob/1e354f583d87d25b7289aaf5234b03725e5527af/ecnu_net.py#L111-L116

服务器有可能会配置两个或更多网卡（一个负责外网上网，其他的负责局域网内的流量），这里通过创建一个临时socket来拿到外网网卡的对应ip. 假设外网的名字是`eno1`的话，那么只要 eno1 与其所在的路由器能够连接就可以了，并不需要 `eno1` 真正ping通 `DNS_SERVER`。

如果`eno1`直连的路由器(非DHCP模式）负载过高的话有可能会出现丢包等现象，就会导致类似的错误发生。
