### ISSUE TITLE
logout失败

### ISSUE THREAD

**Issue by xingyezn** [johnnychen94/ecnu-net-login#2]
我调用:
ecnu_net --logout
反馈回来是：
![image](https://user-images.githubusercontent.com/37822579/172061834-e2d004ac-d18e-42e7-bd29-9cacbf6f4639.png)
一直反复，也不行

**Comment by johnnychen94** [comment]
这有可能是 https://github.com/johnnychen94/ecnu-net-login/blob/25ee222e09c7f37b906f4fc93c1ba5742353a583/ecnu_net.py#L37-L48 里的网址需要更新导致的。
目前的策略是超过 60% 的网址能够连接就认为通了，反之认为不通。现在应该是有超过 60% 的网址不通过网关登录就可以直接访问了。

如果可以的话方便更新一下这个列表么？

这里其实应该是已经成功 login/logout 了，但可能除了返回的测试结果不对有些奇怪以外，倒是不影响正常功能..

**Comment by xingyezn** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已经收到，我会尽快回复你。

**Comment by xingyezn** [comment]
好的我去试试

**Comment by johnnychen94** [comment]
如果试好了提一个 Pull Request 的话就再好不过了 😆
