### ISSUE TITLE
命令行报错

### ISSUE THREAD

**Issue by Eipgen** [johnnychen94/ecnu-net-login#5]
命令行报错，看不太懂这个证书是啥
```
curl --ciphers 'DEFAULT:@SECLEVEL=1' -d "action=login&username=id&password=passwd&ac_id=1&save_me=0&ajax=1" "https://login.ecnu.edu.cn/srun_portal_pc.php?ac_id=1&"
```

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by johnnychen94** [comment]
你用的是这个仓库的脚本么？这个仓库是纯 python 代码应该不涉及 curl

**Comment by johnnychen94** [comment]
看起来是 #4 的脚本

cc: @tianyilt

**Comment by Eipgen** [comment]
搞定了，哈哈，免去ssl 密码就好了
```
curl -k -d "action=login&username=stuid&password=passwd&ac_id=1&ajax=1" https://login.ecnu.edu.cn/include/auth_action.php
```

**Comment by qqliang** [comment]
> 搞定了，哈哈，免去ssl 密码就好了
> 
> ```
> curl -k -d "action=login&username=stuid&password=passwd&ac_id=1&ajax=1" https://login.ecnu.edu.cn/include/auth_action.php
> ```

你好，我现在使用curl命令登录时提示如下错误，请教一下您知道如何处理？
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by tianyilt** [comment]
> > 搞定了，哈哈，免去ssl 密码就好了
> > ```
> > curl -k -d "action=login&username=stuid&password=passwd&ac_id=1&ajax=1" https://login.ecnu.edu.cn/include/auth_action.php
> > ```
> 
> 你好，我现在使用curl命令登录时提示如下错误，请教一下您知道如何处理？
> 
> <title>302 Found</title>
> # 302 Found
> nginx

今天信息办有了大更新，所以要重新抓包写脚本了

**Comment by Eipgen** [comment]
> > 搞定了，哈哈，免去ssl 密码就好了
> > ```
> > curl -k -d "action=login&username=stuid&password=passwd&ac_id=1&ajax=1" https://login.ecnu.edu.cn/include/auth_action.php
> > ```
> 
> 你好，我现在使用curl命令登录时提示如下错误，请教一下您知道如何处理？
> 
> <title>302 Found</title>
> # 302 Found
> nginx
现在还不晓得咋整

**Comment by qqliang** [comment]
> > > 搞定了，哈哈，免去ssl 密码就好了
> > > ```
> > > curl -k -d "action=login&username=stuid&password=passwd&ac_id=1&ajax=1" https://login.ecnu.edu.cn/include/auth_action.php
> > > ```
> > 
> > 
> > 你好，我现在使用curl命令登录时提示如下错误，请教一下您知道如何处理？
> > <title>302 Found</title>
> > # 302 Found
> > nginx
> 
> 今天信息办有了大更新，所以要重新抓包写脚本了

求指导怎么抓包实现登录

**Comment by Eipgen** [comment]
> > > > 搞定了，哈哈，免去ssl 密码就好了
> > > > ```
> > > > curl -k -d "action=login&username=stuid&password=passwd&ac_id=1&ajax=1" https://login.ecnu.edu.cn/include/auth_action.php
> > > > ```
> > > 
> > > 
> > > 你好，我现在使用curl命令登录时提示如下错误，请教一下您知道如何处理？
> > > <title>302 Found</title>
> > > # 302 Found
> > > nginx
> > 
> > 
> > 今天信息办有了大更新，所以要重新抓包写脚本了
> 
> 求指导怎么抓包实现登录
https://billc.oss-cn-shanghai.aliyuncs.com/v2/file/2023/07/17/ECNU-linux%E5%AE%A2%E6%88%B7%E7%AB%AF.zip
学校有这个，
